### PR TITLE
[CO-240] Use k8s-app label instead of app for consistency with

### PR DESCRIPTION
**Pull request by davidewatson**
chart-fluent-bit, etc.

### CODE REVIEW

**Comment by davidewatson** [comment]
# Preface

DO_NOT_MERGE because [prometheus-operator](https://github.com/coreos/prometheus-operator/tree/master/helm) has the opposite convention. We should consider changing fluent-bit instead.

# Chapter 1

Samsung's [chart-fluent-bit](https://github.com/samsung-cnct/chart-fluent-bit/blob/master/fluent-bit/templates/daemonset.yaml) uses the label `k8s-app` instead of `app`. While I prefer `app`, the world appears to have gone the other way:

https://github.com/kubernetes/kops/issues/1226
https://github.com/heptio/aws-quickstart/issues/113
https://github.com/kubernetes-incubator/kubespray/issues/1129

**Comment by DStorck** [comment]
would we need to update the service file as well to reflect this change with the selector. @davidewatson do you think we should still be considering this PR ?

**Comment by davidewatson** [comment]
Yes, all components for an app should share the same labels for grouping purposes. No, I don't think this PR is necessary.

**Comment by DStorck** [comment]
closing for now. we can reopen , or revisit this concept later if we feel the need.

**Pull request closed without merging**
